### PR TITLE
[JOB202201 ] Refactor basic.md

### PR DESCRIPTION
**Pull request by byte-me-stan**
Rewrite the # Kernel Basics session.

### CODE REVIEW

**Comment by byte-me-stan** [comment]
Apply for JOB202201

**Comment by byte-me-stan** [comment]
Applying for JOB202201. Checking through the source code to get better understanding of implementation for rest of the document.

**Review by mysterywolf — APPROVED** [review]
Thank you for your PR!😃

**Comment by mysterywolf** [comment]
Thank you~

**Comment by byte-me-stan** [comment]
@mysterywolf Will be more commits for rest of the sessions.

**Comment by mysterywolf** [comment]
Thank you.😀 Just remeber that you need to delete your forked repository and fork it again, then create a new branch to commit. Otherwise, it could cause a conflict. Don't directly use master branch to commit.

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/community-activities/blob/master/README.md Don't forget to register your name or github ID at there. I suggest you to move to the next chapter, because the first chapter has been registered by other people, but if you want to keep contributing to this chapter, that's ok.😀

**Pull request merged**
